default['campfire_handler']['ip']                     = 'change_me_ip'
default['campfire_handler']['stack']                  = 'change_me_stack'
default['campfire_handler']['campfire']['token']      = 'change_me_token'
default['campfire_handler']['campfire']['room_id']    = 'change_me_room_id'
default['campfire_handler']['campfire']['subdomain']  = 'change_me_subdomain'
